// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC1AdminAddProductFailed', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })


  it('TC1AdminAddProductFailed', async function() {
    // Test name: TC1AdminAddProductFailed
    // Step # | name | target | value
    // 1 | open | /item | 
    await driver.get("http://192.168.3.111:8042/Item")
    // 2 | setWindowSize | 1118x492 | 
    await driver.manage().window().setRect({ width: 1118, height: 492 })
    // 3 | click | id=AdminUsername | 
    await driver.findElement(By.id("AdminUsername")).click()
    // 4 | type | id=AdminUsername | Tananya
    await driver.findElement(By.id("AdminUsername")).sendKeys("Tananya")
    // 5 | type | id=AdminPassword | Tanya123
    await driver.findElement(By.id("AdminPassword")).sendKeys("Tanya123")
    // 6 | click | name=name | 
    await driver.findElement(By.name("name")).click()
    // 7 | click | linkText=Add New Item | 
    await driver.findElement(By.linkText("Add New Item")).click()
    // 8 | click | id=ItemCode | 
    await driver.findElement(By.id("ItemCode")).click()
    // 9 | type | id=ItemCode | rrr
    await driver.findElement(By.id("ItemCode")).sendKeys("rrr")
    // 10 | click | id=ItemName | 
    await driver.findElement(By.id("ItemName")).click()
    // 11 | type | id=ItemName | rrr
    await driver.findElement(By.id("ItemName")).sendKeys("rrr")
    // 12 | click | id=Description | 
    await driver.findElement(By.id("Description")).click()
    // 13 | type | id=Description | eee
    await driver.findElement(By.id("Description")).sendKeys("eee")
    // 14 | click | css=.col-md-4:nth-child(5) > .from-group | 
    await driver.findElement(By.css(".col-md-4:nth-child(5) > .from-group")).click()
    // 15 | click | css=.col-md-4:nth-child(3) > .from-group | 
    await driver.findElement(By.css(".col-md-4:nth-child(3) > .from-group")).click()
    // 16 | type | id=ItemName | aaa
    await driver.findElement(By.id("ItemName")).sendKeys("aaa")
    // 17 | click | css=.col-md-4:nth-child(5) > .from-group | 
    await driver.findElement(By.css(".col-md-4:nth-child(5) > .from-group")).click()
    // 18 | type | id=ItemPrice | 20
    await driver.findElement(By.id("ItemPrice")).sendKeys("20")
    // 19 | click | id=btnSave | 
    await driver.findElement(By.id("btnSave")).click()
    // 20 | webdriverChooseOkOnVisibleConfirmation | ok | 
/*     await driver.switchTo().alert().accept() */
    // 21 | click | linkText=Log Out | 
    await driver.sleep(500);
    //add new
    try{
      await driver.findElement(By.linkText('There is some problem to add Item')).click();
  
      // Wait for the alert to be displayed
      await driver.wait(until.alertIsPresent());
      
      // Store the alert in a variable
      let alert = await driver.switchTo().alert();
      
      //Store the alert text in a variable
      let alertText = await alert.getText();
      
      //Press the OK button
      await alert.accept();
  }catch(err2) {
      console.log("Error2: " + err2);
  };
    await driver.findElement(By.linkText("Log Out")).click()
  })
})
