// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC2AdminAddProductSuccess', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC2AdminAddProductSuccess', async function() {
    // Test name: TC2AdminAddProductSuccess
    // Step # | name | target | value
    // 1 | open | http://192.168.3.111:8042/User/AdminLogin | 
    await driver.get("http://192.168.3.111:8042/User/AdminLogin")
    // 2 | setWindowSize | 1680x737 | 
    await driver.manage().window().setRect({ width: 1680, height: 737 })
    // 3 | click | id=AdminUsername | 
    await driver.findElement(By.id("AdminUsername")).click()
    // 4 | type | id=AdminUsername | Tananya
    await driver.findElement(By.id("AdminUsername")).sendKeys("Tananya")
    // 5 | type | id=AdminPassword | Tanya123
    await driver.findElement(By.id("AdminPassword")).sendKeys("Tanya123")
    // 6 | click | name=name | 
    await driver.findElement(By.name("name")).click()
    // 7 | click | linkText=Add New Item | 
    await driver.findElement(By.linkText("Add New Item")).click()
    // 8 | click | id=ItemCode | 
    await driver.findElement(By.id("ItemCode")).click()
    // 9 | type | id=ItemCode | aaa
    await driver.findElement(By.id("ItemCode")).sendKeys("Adidas 001")
    // 10 | click | id=ItemName | 
    await driver.findElement(By.id("ItemName")).click()
    // 11 | type | id=ItemName | aaa
    await driver.findElement(By.id("ItemName")).sendKeys("Adidas 001")
    // 12 | click | id=Description | 
    await driver.findElement(By.id("Description")).click()
    // 13 | type | id=Description | aaa
    await driver.findElement(By.id("Description")).sendKeys("Adidas 001")
    // 14 | click | css=.col-md-4:nth-child(5) > .from-group | 
    await driver.findElement(By.css(".col-md-4:nth-child(5) > .from-group")).click()
    // 15 | type | id=ItemPrice | 20
    await driver.findElement(By.id("ItemPrice")).sendKeys("20")
    // 16 | click | id=ImagePath | 
   /*  await driver.findElement(By.id("ImagePath")).click()
    // 17 | type | id=ImagePath | C:\Users\admin\Downloads\T-Shirt2.jfif
    await driver.findElement(By.id("ImagePath")).sendKeys("C:\\Users\\admin\\Downloads\\T-Shirt2.jfif")
    // 18 | click | id=ImagePath | 
    await driver.findElement(By.id("ImagePath")).click() */

    try{
      await driver.findElement(By.xpath(`/html[1]/body[1]/div[2]/div[1]/div[6]/div[1]/input[1]`))
      .sendKeys(__dirname+"\\adidas_shoe.jfif");
      
 } catch (error){
     console.log(error);
 }
    // 19 | click | id=btnSave | 
    await driver.findElement(By.id("btnSave")).click()
    await driver.sleep(500);
    try{
      await driver.findElement(By.linkText('Item is added Successfully')).click();
  
      // Wait for the alert to be displayed
      await driver.wait(until.alertIsPresent());
      
      // Store the alert in a variable
      let alert = await driver.switchTo().alert();
      
      //Store the alert text in a variable
      let alertText = await alert.getText();
      
      //Press the OK button
      await alert.accept();
  }catch(err2) {
      console.log("Error2: " + err2);
  };
  await driver.findElement(By.css(`a[href="/Product"]`)).click();
  
          //assert
          let todoText = await driver.findElement(By.xpath("//tbody/tr[2]/td[2]")).getText().then(function(value){
              return value
          });
          assert.strictEqual(todoText,"Adidas 001"); 
      
    // 21 | click | linkText=Item List | 
    await driver.findElement(By.linkText("Item List")).click()
    // 22 | click | linkText=Log Out | 
    await driver.findElement(By.linkText("Log Out")).click()
  })
})
