// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC3AdminDeleteProductSuccess', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC3AdminDeleteProductSuccess', async function() {
    // Test name: TC3AdminDeleteProductSuccess
    // Step # | name | target | value
    // 1 | open | http://192.168.3.111:8042/User/AdminLogin | 
    await driver.get("http://192.168.3.111:8042/User/AdminLogin")
    // 2 | setWindowSize | 1680x737 | 
    await driver.manage().window().setRect({ width: 1680, height: 737 })
    // 3 | click | id=AdminUsername | 
    await driver.findElement(By.id("AdminUsername")).click()
    // 4 | type | id=AdminUsername | Tananya
    await driver.findElement(By.id("AdminUsername")).sendKeys("Tananya")
    // 5 | type | id=AdminPassword | Tanya123
    await driver.findElement(By.id("AdminPassword")).sendKeys("Tanya123")
    // 6 | click | name=name | 
    await driver.findElement(By.name("name")).click()
    // 7 | click | linkText=Delete | 
    await driver.findElement(By.linkText("Delete")).click()
    // 8 | click | css=.btn | 
    await driver.findElement(By.css(".btn")).click()
    // 9 | click | linkText=Log Out | 
    await driver.findElement(By.linkText("Log Out")).click()
    // 10 | close |  | 
    await driver.close()
  })
})
