// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC5CutomerRegisterSuccess', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC5CutomerRegisterSuccess', async function() {
    // Test name: TC5CutomerRegisterSuccess
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://192.168.3.111:8042")
    // 2 | setWindowSize | 1680x737 | 
    await driver.manage().window().setRect({ width: 1680, height: 737 })
    // 3 | click | id=loginlink | 
    await driver.findElement(By.id("loginlink")).click()
    // 4 | click | linkText=Customer Register | 
    await driver.findElement(By.linkText("Customer Register")).click()
    // 5 | click | id=FirstName | 
    await driver.findElement(By.id("FirstName")).click()
    // 6 | type | id=FirstName | Tanay2
    await driver.findElement(By.id("FirstName")).sendKeys("Tanay2")
    // 7 | type | id=LastName | Asava2
    await driver.findElement(By.id("LastName")).sendKeys("Asava2")
    // 8 | type | id=UserName | Tanya1232
    await driver.findElement(By.id("UserName")).sendKeys("Tanya1232")
    // 9 | type | id=Password | Tanya123
    await driver.findElement(By.id("Password")).sendKeys("Tanya123")
    // 10 | type | id=ConfirmPassword | Tanya123
    await driver.findElement(By.id("ConfirmPassword")).sendKeys("Tanya123")
    // 11 | type | id=Email | Tanya@hotmail.com
    await driver.findElement(By.id("Email")).sendKeys("Tanya@hotmail.com")
    // 12 | click | css=.btn | 
    await driver.findElement(By.css(".btn")).click()
    // 13 | click | id=loginlink | 
    await driver.findElement(By.id("loginlink")).click()
    // 14 | close |  | 
    await driver.close()
  })
})
