// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('TC11CutomerLogoutSuccess', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC11CutomerLogoutSuccess', async function() {
    // Test name: TC11CutomerLogoutSuccess
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://192.168.3.111:8042/")
    // 2 | setWindowSize | 1680x737 | 
    await driver.manage().window().setRect({ width: 1680, height: 737 })
    // 3 | click | id=loginlink | 
    await driver.findElement(By.id("loginlink")).click()
    // 4 | click | id=UserName | 
    await driver.findElement(By.id("UserName")).click()
    // 5 | type | id=UserName | Tanya1232
    await driver.findElement(By.id("UserName")).sendKeys("Tanya1232")
    // 6 | type | id=Password | Tanya123
    await driver.findElement(By.id("Password")).sendKeys("Tanya123")
    // 7 | click | name=name | 
    await driver.findElement(By.name("name")).click()
    // 8 | click | linkText=Log Out | 
    await driver.findElement(By.linkText("Log Out")).click()
    // 9 | close |  | 
    await driver.close()
  })
})
