describe('TC5CutomerRegisterSuccess', () => {
  it('TC5 Cutomer Register Success', () => {
    cy.visit('http://192.168.3.111:8042')
    cy.get('#loginlink').click()
    cy.get('td > #loginlink').click()
    cy.get('#FirstName').type('TananyaTest')
    cy.get('#LastName').type('AsaTest')
    cy.get('#UserName').type('TananyaTest')
    cy.get('#Password').type('1234')
    cy.get('#ConfirmPassword').type('1234')
    cy.get('#Email').type('AsaTest@hotmail.com')
    cy.get('[type="submit"]').click()
    cy.get('.btn').click()    
    cy.get('.label-success').click.toString(`Registration successful.`)
    cy.viewport(1350, 700)
    cy.screenshot()
   // cy.get('#logoutForm > a').click()
  })
})