describe('TC14AdminAddNewMenu', () => {
  it('TC14 Admin Add New Menu', () => {
    cy.visit('http://localhost:8044/User/AdminLogin')
    cy.get('#AdminUsername').type('Tananya1')
    cy.get('#AdminPassword').type('Tanya123')
    cy.get(`input[value="Login"]`).click()
    cy.get(`a[href="/Order/ItemIndex"]`).click()
    cy.get(`a[href="/Order/AddItem"]`).click()
    cy.get('#ItemName').type('13 - Green Tea')
    cy.get(`#ItemPrice`).clear("")
    cy.get(`#ItemPrice`).type("5.00")
    cy.get(`input[value="Create"]`).click()
    cy.get(`div[class="container body-content"] div a`).click()
    cy.get('body > div:nth-child(2) > table:nth-child(3) > tbody:nth-child(1) > tr:nth-child(14) > td:nth-child(2)')
    .click.toString(`13 - Green Tea`)
    cy.screenshot()
  //  cy.get(`#logoutForm`).click()
  })
})