const {test, expect} = require('@playwright/test');
test('TC25AfterPaymentSuccessClickonOrderlistPage',async ({page})=>{
    await page.goto("http://localhost:8044/User/AdminLogin");
    await page.locator('#AdminUsername').type('Tananya1')
    await page.locator('#AdminPassword').type('Tanya123')
    await page.locator('input[value="Login"]').click()
    await page.locator(`select[name="Customer"]`).type("Customer Z")
    await page.locator(`select[name="Item"]`).type("1 - Signature Tonkotsu Chashu Ramen")
    await page.waitForTimeout(500)
    await page.locator('#txtQuantity').fill("")
    await page.locator('#txtQuantity').type("1")
    await page.locator(`#btnAddToList`).click()
    await page.locator(`select[name="Item"]`).type("2 - Oh my HOT!! Tonkotsu Chashu Ramen")
    await page.locator('#txtQuantity').fill("")
    await page.locator('#txtQuantity').type("2")
    await page.locator(`#btnAddToList`).click()
    await page.locator(`select[name="Item"]`).type("3 - Nostalgic Japanese Soy Chicken Ramen")
    await page.locator('#txtQuantity').fill("")
    await page.locator('#txtQuantity').type("2")
    await page.locator(`#btnAddToList`).click()
    await page.locator(`#btnCheckOut`).click()
    await page.locator(`#txtPaymentAmount`).fill("")
    await page.locator(`#txtPaymentAmount`).type("89.40")
    await page.locator(`#txtReturnTotal`).type("0")
    await page.locator(`#btnPayment`).click()
    await page.locator(`a[href="/Order/OrderIndex"]`).click()
    page.locator('tbody tr:nth-child(2) td:nth-child(5)')
    .click.toString(`89.40`)
    await page.locator(`#logoutForm`).click()
});